# Generated by Django 3.1.7 on 2022-04-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('published_time', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('intro', models.TextField(verbose_name='描述')),
                ('pic', models.FileField(max_length=64, upload_to='book_cover', verbose_name='封面图片')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('like_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_purchase', models.BooleanField(default=False, verbose_name='是否可购买')),
                ('price', models.FloatField(default=66.66, verbose_name='单价')),
                ('inventory', models.IntegerField(blank=True, default=9999, null=True, verbose_name='库存')),
                ('purchase_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='销售数量')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RateBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_book', to='book.book', verbose_name='图书id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
                'db_table': 'rate_book',
            },
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('price', models.FloatField(default=66.66, verbose_name='单价')),
                ('purchase_num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('all_price', models.FloatField(default=66.66, verbose_name='总价')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='手机号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('order_status', models.CharField(choices=[('0', '待支付'), ('1', '已支付'), ('2', '待收货'), ('3', '已收货')], default='0', max_length=10, verbose_name='订单状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_book', to='book.book', verbose_name='图书id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '购书清单',
                'verbose_name_plural': '购书清单',
                'db_table': 'purchase_list',
            },
        ),
        migrations.CreateModel(
            name='LikeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_book', to='book.book', verbose_name='图书id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '图书点赞',
                'verbose_name_plural': '图书点赞',
                'db_table': 'like_book',
            },
        ),
        migrations.CreateModel(
            name='CommentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('like_users', models.TextField(blank=True, default=None, null=True, verbose_name='点赞用户')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='书籍')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '图书评论',
                'verbose_name_plural': '图书评论',
                'db_table': 'comment_book',
            },
        ),
        migrations.CreateModel(
            name='CollectBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_book', to='book.book', verbose_name='图书id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '图书收藏',
                'verbose_name_plural': '图书收藏',
                'db_table': 'collect_book',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='book.tags', verbose_name='标签'),
        ),
    ]
