# Generated by Django 3.1.7 on 2022-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pic_down',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='card_cover', verbose_name='卡片背面'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pic_up',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='card_cover', verbose_name='卡片正面'),
        ),
    ]
