# Generated by Django 3.1.7 on 2022-04-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20220415_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['release_name']},
        ),
    ]
