# Generated by Django 3.1.7 on 2022-04-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20220419_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['release_year']},
        ),
    ]
