# Generated by Django 3.1.7 on 2022-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20220419_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=128, verbose_name='系列')),
                ('card_type', models.CharField(max_length=64, verbose_name='类型')),
                ('card_set', models.CharField(max_length=64, verbose_name='具体类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=32, verbose_name='球员')),
                ('card_team', models.CharField(max_length=32, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
                ('has_owned', models.BooleanField(default=False, verbose_name='是否拥有')),
                ('pic_up', models.FileField(blank=True, max_length=64, null=True, upload_to='card_cover', verbose_name='卡片正面')),
                ('pic_down', models.FileField(blank=True, max_length=64, null=True, upload_to='card_cover', verbose_name='卡片背面')),
                ('intro', models.TextField(default='', verbose_name='背面故事')),
            ],
            options={
                'db_table': 'all_card',
                'ordering': ['release_year'],
            },
        ),
    ]
