# Generated by Django 3.1.7 on 2022-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_allcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercard',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='othercard',
            name='has_owned',
        ),
        migrations.RemoveField(
            model_name='othercard',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='othercard',
            name='pic_down',
        ),
        migrations.RemoveField(
            model_name='othercard',
            name='pic_up',
        ),
    ]
