# Generated by Django 3.1.7 on 2022-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20220525_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcard',
            name='card_set',
        ),
        migrations.RemoveField(
            model_name='allcard',
            name='has_owned',
        ),
        migrations.RemoveField(
            model_name='allcard',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='allcard',
            name='pic_down',
        ),
        migrations.RemoveField(
            model_name='allcard',
            name='pic_up',
        ),
        migrations.AddField(
            model_name='othercard',
            name='card_type',
            field=models.CharField(default='', max_length=64, verbose_name='类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercard',
            name='has_owned',
            field=models.BooleanField(default=False, verbose_name='是否拥有'),
        ),
        migrations.AddField(
            model_name='othercard',
            name='intro',
            field=models.TextField(default='', verbose_name='背面故事'),
        ),
        migrations.AddField(
            model_name='othercard',
            name='pic_down',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='other_card_cover', verbose_name='卡片背面'),
        ),
        migrations.AddField(
            model_name='othercard',
            name='pic_up',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='other_card_cover', verbose_name='卡片正面'),
        ),
    ]
