# Generated by Django 3.1.7 on 2022-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_auto_20220527_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcard',
            name='card_team',
            field=models.CharField(max_length=2048, verbose_name='球队'),
        ),
    ]
