# Generated by Django 3.1.7 on 2022-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20220527_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_2010_2011',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2010_2011',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2011_2012',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2011_2012',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2012_2013',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2012_2013',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2013_2014',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2013_2014',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2014_2015',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2014_2015',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2015_2016',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2015_2016',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2016_2017',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2016_2017',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2017_2018',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2017_2018',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2018_2019',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2018_2019',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2019_2020',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2019_2020',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2020_2021',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2020_2021',
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Card_2021_2022',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_numner', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2021_2022',
                'ordering': ['release_year'],
            },
        ),
    ]
