# Generated by Django 3.1.7 on 2022-06-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_card_2010_2011_card_2011_2012_card_2012_2013_card_2013_2014_card_2014_2015_card_2015_2016_card_2016_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_2010_2011',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2011_2012',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2012_2013',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2013_2014',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2014_2015',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2015_2016',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2016_2017',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2017_2018',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2018_2019',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2019_2020',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2020_2021',
            old_name='card_numner',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card_2021_2022',
            old_name='card_numner',
            new_name='card_number',
        ),
    ]
