# Generated by Django 3.1.7 on 2023-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_card_2009_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_2022_2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=32, verbose_name='发行年份')),
                ('release_name', models.CharField(max_length=256, verbose_name='系列')),
                ('card_type', models.CharField(max_length=256, verbose_name='类型')),
                ('card_number', models.IntegerField(default=0, verbose_name='编号')),
                ('card_player', models.CharField(max_length=2048, verbose_name='球员')),
                ('card_team', models.CharField(max_length=2048, verbose_name='球队')),
                ('card_seq', models.IntegerField(default=0, verbose_name='限量')),
            ],
            options={
                'db_table': 'card_2022_2023',
                'ordering': ['release_year'],
            },
        ),
    ]
